apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: es-master00
  namespace: elasticsearch-demo-app
spec:
  rsync:
    sshKeys: volsync-rsync-dst-dest-ssh
    destinationPVC: es-master00
    serviceType: LoadBalancer
    copyMethod: Snapshot
    capacity: 10Gi
    accessModes: [ReadWriteOnce]
    storageClassName: lvms-vg1
    volumeSnapshotClassName: lvms-vg1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: es-master00-data
  namespace: elasticsearch-demo-app
spec:
  rsync:
    sshKeys: volsync-rsync-dst-dest-ssh
    destinationPVC: es-master00-data
    serviceType: LoadBalancer
    copyMethod: Snapshot
    capacity: 10Gi
    accessModes: [ReadWriteOnce]
    storageClassName: lvms-vg1
    volumeSnapshotClassName: lvms-vg1

