apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: elasticsearch-demo-app
  namespace: elasticsearch-demo-app
spec:
  selector:
    matchExpressions:
    - key: name  
      operator: In
      values:
      - elasticsearch-demo-app
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
