---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: letsencrypt
  namespace: elasticsearch-demo-app
---
kind: Service
apiVersion: v1
metadata:
  name: es-main-svc
  namespace: elasticsearch-demo-app
spec:
  ports:
    - name: elasticsearch
      protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
    elasticsearch: main
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: elasticsearch
  namespace: elasticsearch-demo-app
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: letsencrypt
  labels:
    app: elasticsearch
    role: api
spec:
  host: elasticsearch.apps.development.wels.home
  to:
    kind: Service
    name: es-main-svc
  port:
    targetPort: elasticsearch
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: install-scripts
  namespace: elasticsearch-demo-app
data:
  elasticsearch.sh: |-
    cat << EOF > /etc/yum.repos.d/elastic.repo
    [elasticsearch]
    name=Elasticsearch repository for 8.x packages
    baseurl=https://artifacts.elastic.co/packages/8.x/yum
    gpgcheck=1
    gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled=0
    autorefresh=1
    type=rpm-md
    EOF
    update-crypto-policies --set DEFAULT:SHA1
    rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dnf install -y --enablerepo=elasticsearch elasticsearch-8.7.0
    update-crypto-policies --set DEFAULT
    systemctl daemon-reload
    mkdir -p /srv/elasticsearch/config
    mkdir -p /srv/elasticsearch/data
    chown elasticsearch:elasticsearch /srv/elasticsearch -R
    mkfs.xfs /dev/disk/by-id/virtio-datadisk
    config=$(ls -1 /dev/disk/by-id/virtio-00yaml)
    mount $config /srv/elasticsearch/config
    mount /dev/disk/by-id/virtio-datadisk /srv/elasticsearch/data
    echo "$config /srv/elasticsearch/config iso9660 defaults 0 0" >> /etc/fstab
    echo '/dev/disk/by-id/virtio-datadisk /srv/elasticsearch/data   xfs defaults 0 0' >> /etc/fstab
    mv /etc/elasticsearch/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml.org
    mv /etc/elasticsearch/jvm.options       /etc/elasticsearch/jvm.options.org
    ln -sf /srv/elasticsearch/config/elasticsearch.conf /etc/elasticsearch/elasticsearch.yml
    ln -sf /srv/elasticsearch/config/jvm.options        /etc/elasticsearch/jvm.options
    systemctl enable elasticsearch --now
  system.sh: |-
    cert=$(ls -1 /dev/disk/by-id/virtio-00cert)
    mount $cert /etc/cockpit/ws-certs.d/
    if [ -f "/etc/cockpit/ws-certs.d/tls.crt" ]; then echo "$cert /etc/cockpit/ws-certs.d/ xfs defaults 0 0" >> /etc/fstab;
    else umount $cert; fi
    systemctl enable cockpit.socket --now
immutable: false
