---
apiVersion: v1
kind: Service
metadata:
  name: coordinate
  namespace: elasticsearch-demo-app
spec:
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
    - name: elasticsearch-discovery
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch
    elasticsearch: coordinate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinate
  namespace: elasticsearch-demo-app
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"kubevirt.io/v1","kind":"VirtualMachine","name":"es-master00"}]'
  labels:
    app.kubernetes.io/part-of: elasticsearch
    app.openshift.io/runtime: elastic
    app.openshift.io/name: coordinate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      elasticsearch: coordinate
  template:
    metadata:
      labels:
        app: elasticsearch
        elasticsearch: coordinate
    spec:
      containers:
        - name: coordinate
          image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0-amd64
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
          - name: node.name
            value: coordinate
          - name: cluster.name
            value: demo
          - name: xpack.security.enabled
            # Set to true to enable security
            value: "false"
          - name: xpack.security.transport.ssl.enabled
            # Set to true to enable ssl for transport
            value: "false"
          - name: xpack.security.http.ssl.enabled
            # Set to true to enable ssl for http
            value: "false"
          - name: discovery.seed_hosts
            # If multiple VMs, add more here with a comma separated list
            value: es-master00
          - name: node.roles
            value: "[]"
          - name: network.publish_host
            value: coordinate.elasticsearch-demo-app.svc.cluster.local
          - name: network.host
            value: _site_
          resources: {}
      restartPolicy: Always
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: coordinate
  namespace: elasticsearch-demo-app
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: letsencrypt
  labels:
    app: elasticsearch
    role: coordinate
spec:
  host: coordinate.apps.development.wels.home
  to:
    kind: Service
    name: coordinate
  port:
    targetPort: elasticsearch
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
