apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-sync-ownerref
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvc-sync-ownerref
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvc-sync-ownerref
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pvc-sync-ownerref
subjects:
- kind: ServiceAccount
  name: post-sync-ownerref
---
apiVersion: batch/v1
kind: Job
metadata:
  name: remove-ownerref
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: post-sync-ownerref
      restartPolicy: Never
      containers:
      - image: quay.io/appuio/oc:v4.12
        command:
          ["/bin/sh"]
        args: ["-c",
      "oc patch pvc es-main00-data --type=json -p=\"[{'op':'remove', 'path':'/metadata/ownerReferences'}]\" || true && oc patch pvc es-main00 --type=json -p=\"[{'op':'remove', 'path':'/metadata/ownerReferences'}]\" || true"]
        imagePullPolicy: IfNotPresent
        name: oc

