apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: es-master00
  namespace: elasticsearch-demo-app
spec:
  sourcePVC: es-master00
  trigger:
    # Replicate every 5 minutes
    schedule: "*/5 * * * *"
  rsyncTLS:
    # The name of the Secret we just created
    keySecret: tls-key-secret-master00
    # The LoadBalancer address from the ReplicationDestination
    address: 192.168.1.37
    copyMethod: Snapshot
    storageClassName: lvms-vg1
    volumeSnapshotClassName: lvms-vg1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: es-master00-data
  namespace: elasticsearch-demo-app
spec:
  sourcePVC: es-master00-data
  trigger:
    # Replicate every 5 minutes
    schedule: "*/5 * * * *"
  rsyncTLS:
    # The name of the Secret we just created
    keySecret: tls-key-secret-data
    # The LoadBalancer address from the ReplicationDestination
    address: 192.168.1.36
    copyMethod: Snapshot
    storageClassName: lvms-vg1
    volumeSnapshotClassName: lvms-vg1
